---
title: "Temple Predicting Proposal"
author: SloppyLions
format: html
---
Brian Anderson - Computer Science
Jared Linares- Computer Science
Seth Linares - Computer Science
David Mumford - Computer Science
Kristin Thumstedter - Computer Science

## Plan Overview
To predict future temple announcements, our team combined the Safegraph pattern data and the census data to observe current operating temple attendance traffic. If there is a trend with certain temples having high usage and then a new temple to help relieve the traffic stress, we could anticipate that the brethren had a higher desire to create another temple in that area. The census data helps to create an estimated distance to the temple and each county's traffic to that particular temple.

## SafeGraph Data



## Census Data




## Successfully Accomplished
Our teams have identified some key aspects to indicate that our data manipulation and trend tracking were correct and could be used to predict future temples. We will know if it is successful if it predicts future and recently announced temples.   

